- position: W3C Invited Expert, 2021-Present
  at: ARIA Working Group
  url: https://www.w3.org/groups/wg/aria/participants#:~:text=Frank%20Elavsky
- position: Organizer, Co-Founder
  at: DataVizA11y, 2020-Present
  url: https://github.com/dataviza11y/Why-We-Exist
- position: Volunteer Analyst, 2021
  at: City of San Francisco Covid-19 Data Team
  url: https://sf.gov/resource/2021/covid-19-data-and-reports
